# Generated by Django 5.2 on 2025-05-19 16:50

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarioentrada',
            name='texto',
            field=django_quill.fields.QuillField(),
        ),
    ]
