# Generated by Django 5.2 on 2025-05-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='peso',
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
