# Generated by Django 5.2 on 2025-05-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_pregunta_peso_opcionrespuesta_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
