# Generated by Django 5.2 on 2025-05-29 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('aburrimiento', 'Aburrimiento'), ('agotamiento', 'Agotamiento'), ('alegria', 'Alegría'), ('amor', 'Amor'), ('ansiedad', 'Ansiedad'), ('calma', 'Calma'), ('compasion', 'Compasión'), ('confusion', 'Confusión'), ('culpa', 'Culpa'), ('duda', 'Duda'), ('envidia', 'Envidia'), ('esperanza', 'Esperanza'), ('frustracion', 'Frustración'), ('gratitud', 'Gratitud'), ('indiferencia', 'Indiferencia'), ('inseguridad', 'Inseguridad'), ('interes', 'Interés'), ('ira', 'Ira'), ('motivacion', 'Motivación'), ('miedo', 'Miedo'), ('nostalgia', 'Nostalgia'), ('orgullo', 'Orgullo positivo'), ('seguridad', 'Seguridad'), ('soledad', 'Soledad'), ('sorpresa', 'Sorpresa'), ('tristeza', 'Tristeza'), ('vergüenza', 'Vergüenza')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.emotionquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question', 'date')},
            },
        ),
    ]
