# Generated by Django 5.2 on 2025-06-03 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmotionResponse',
            new_name='EmotionEntry',
        ),
        migrations.AlterUniqueTogether(
            name='emotionentry',
            unique_together=set(),
        ),
    ]
