# Generated by Django 5.2 on 2025-06-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_emotionresponse_emotionentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionentry',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Muy baja'), (2, '2 - Baja'), (3, '3 - Moderada'), (4, '4 - Alta'), (5, '5 - Muy alta')], default=3),
        ),
    ]
